### ISSUE TITLE
Can I keep the source space?

### ISSUE THREAD

**Issue by drakeet** [Pixplicity/HtmlCompat#14]
Hello, I am happy to find this project and it works very well. But I found a problem:

When I calls: 
```java
HtmlCompat.fromHtml(this, "<strike>    str    ike    </strike>", 0)
```
The `textView` shows:

<del>str ike </del>

This is not what I expected. Can I keep all spaces of the source and apply the `strike` style to them? 

Thanks!

**Comment by drakeet** [comment]
OK, I think I found a solution. Use `HtmlCompat#escapeHtml(text)`.

**Comment by mlagerberg** [comment]
That is regular HTML behaviour. You can try it in your browser and get the same result. To keep the spaces you can use `&nbsp;` instead of a space.
