### ISSUE TITLE
Support for custom <span> handling

### ISSUE THREAD

**Issue by eoinfogarty** [Pixplicity/HtmlCompat#17]
A project Im working on now, we recieve html that has <span> tags with a class attribute. Something like this: 
` Now we are going to use a <span class="span_class">span tag and apply a class to it</span>`

We cant handle this with `TagHandler`. 
`Html` and `HtmlCompact` have basic support for span styles, which means any unsupported tags will get swallowed.

How about about another callback that will let us explicitly handle spans ourselves.

reference https://github.com/Pixplicity/HtmlCompat/pull/16

**Comment by pflammertsma** [comment]
This behavior should be included in 1.1.0, which has been published and should be available shortly.
