### ISSUE TITLE
Question: What is exactly new on recent Android versions that this library provides?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Pixplicity/HtmlCompat#2]
As the repo says:

> Nougat introduced vast improvements to the Html class for converting HTML to spannables.

Is there a list of them on Google's docs websites?
I know for sure that some of the items on the list you've written already existed before.

**Comment by pflammertsma** [comment]
This library only provides a very minimal set of new features. You may want
to explore the SDK versions of various methods in the Http class to
discover which methods are and aren't supported before Nougat.

Some tags have been added in Nougat as well, but they're not documented.
Furthermore, the behavior of callbacks differs between SDK versions.

**Comment by MoeHamoud** [comment]
@AndroidDeveloperLB I think this commit may be of help to you, https://github.com/android/platform_frameworks_base/commit/8b36c0bbd1503c61c111feac939193c47f812190

It looks like they added `ul`, `li` and `span`

**Comment by pflammertsma** [comment]
Also added is some basic CSS styles for text and background colors, text alignment, underline and strikethrough, and line break behavior using flags. There have also been improvements to `toHtml()`.

**Comment by AndroidDeveloperLB** [comment]
Can you please put a list of all the things that this library adds (on the project page), compared to what isn't available on older Android versions ?
