### ISSUE TITLE
HtmlCompat with Picasso

### ISSUE THREAD

**Issue by ccentauri** [Pixplicity/HtmlCompat#21]
How can I load images from `<img>` using Picasso?
I can get image `url ` from `source ` attribute and create Drawable instance, but I can't return for method `getDrawable`

**Comment by pflammertsma** [comment]
Fantastic question. HtmlCompat mostly just backports the Html class itself, so perhaps research a solution that works against the original SDK first. A quick search [gives this SO answer](https://stackoverflow.com/a/33040437/154306), is that a viable solution?

**Comment by ccentauri** [comment]
@pflammertsma  Yes. This is simple solution. Thank you very much!

**Comment by pflammertsma** [comment]
Glad it helps!
