### ISSUE TITLE
<del> or <strike> tag is not working

### ISSUE THREAD

**Issue by IntelliJAbhishek** [Pixplicity/HtmlCompat#22]
I'm using this library in my project but i've seen `<strike>` and `<del>` tags are not working.

        String priceString="<del>123</del>";//model.getPriceHtml();
        Log.e("Price",priceString);
        holder.price.setText(HtmlCompat.fromHtml(mContext,priceString,HtmlCompat.FROM_HTML_MODE_LEGACY));

**Comment by IntelliJAbhishek** [comment]
Sorry its was my fault I had done various styling on `TextView`, closing this issue.

**Comment by pflammertsma** [comment]
Thanks for circling back on this!
