### ISSUE TITLE
Sample images in the library?

### ISSUE THREAD

**Issue by mrsasha** [Pixplicity/HtmlCompat#23]
Hi,

I was looking through my app APK and noticed a strange 30K `sample.png` and realized it comes from your library. Is there a reason for it being there and not in the `sample` project? We have an Instant App which has APKs limited to 4MB so every KB counts.

Thanks!

**Comment by pflammertsma** [comment]
Excellent remark, it's totally misplaced as it should be in the sample module. I'll try find a moment to publish a new version soon.

**Comment by pflammertsma** [comment]
Released in 1.1.1.
