### ISSUE TITLE
Library shouldn't include android:allowBackup="true"

### ISSUE THREAD

**Issue by iliakap** [Pixplicity/HtmlCompat#8]
Is there a reason there is allowBackaup attribute on the manifest?
Normally that shouldn't be included

https://github.com/Pixplicity/HtmlCompat/blob/master/library/src/main/AndroidManifest.xml#L5

**Comment by pflammertsma** [comment]
No reason other than it's the Android Studio default. Libraries don't need an application declaration at all, and I've removed it.
